sudo:
  required

services:
  - docker

language: java
jdk: oraclejdk8

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

before_install:
  - cd smlr
  - mvn -N io.takari:maven:wrapper

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $D_USER -p $D_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export NAME=serhiion/smlr
  - docker build -t $NAME:$COMMIT .
  - docker tag $NAME:$COMMIT $NAME:$TAG
  - docker push $NAME

#notifications:
#  email:
#    - sergeonishhenko@gmail.com
