language: java
jdk: oraclejdk8

before_install:
  - cd smlr
  - mvn -N io.takari:maven:wrapper

after_success:
  - bash <(curl -s https://codecov.io/bash)

#notifications:
#  email:
#    - sergeonishhenko@gmail.com
